/* ============================================
   auth.js — AWS Cognito + Lambda OTP (replaces Firebase + EmailJS)
   All Firebase and EmailJS references have been removed.
   Config is loaded from config.js (generated by CDK at deploy time).
   ============================================ */

// ─────────────────────────────────────────────
// CONFIG  (set by config.js, generated by CDK)
// ─────────────────────────────────────────────
function _cfg() {
  if (typeof window !== "undefined" && window.APP_CONFIG) return window.APP_CONFIG;
  // Fallback for local dev — copy actual values from CDK outputs
  return {
    COGNITO_REGION:       "us-east-2",
    COGNITO_USER_POOL_ID: "",
    COGNITO_CLIENT_ID:    "",
    API_BASE_URL:         "",
  };
}

// ─────────────────────────────────────────────
// COGNITO REST HELPERS
// Cognito's public-facing JSON API — no SDK needed for browser operations.
// All calls that require admin privileges go through our Lambda endpoints.
// ─────────────────────────────────────────────
async function _cognitoCall(target, payload) {
  const cfg = _cfg();
  const url  = `https://cognito-idp.${cfg.COGNITO_REGION}.amazonaws.com/`;
  const res  = await fetch(url, {
    method:  "POST",
    headers: {
      "Content-Type":  "application/x-amz-json-1.1",
      "X-Amz-Target": `AWSCognitoIdentityProviderService.${target}`,
    },
    body: JSON.stringify(payload),
  });

  const data = await res.json();
  if (!res.ok) {
    // Cognito returns __type and message in the JSON body on error
    const err      = new Error(data.message || "Cognito error");
    err.code       = data.__type || "UnknownError";
    err.statusCode = res.status;
    throw err;
  }
  return data;
}

// ─────────────────────────────────────────────
// API GATEWAY HELPERS
// ─────────────────────────────────────────────
async function _apiPost(path, payload) {
  const url = `${_cfg().API_BASE_URL}/${path}`;
  const res = await fetch(url, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify(payload),
  });
  const data = await res.json();
  if (!res.ok) {
    const err  = new Error(data.error || "API error");
    err.status = res.status;
    err.code   = "api/" + path;
    throw err;
  }
  return data;
}

// ─────────────────────────────────────────────
// REGISTER — Cognito SignUp (public API, no secret needed)
// After sign-up Cognito sends a 6-digit code to the user's email.
// The user must confirm it on confirm.html before they can sign in.
// ─────────────────────────────────────────────
async function registerUser(email, password) {
  const cfg = _cfg();
  return _cognitoCall("SignUp", {
    ClientId:        cfg.COGNITO_CLIENT_ID,
    Username:        email,
    Password:        password,
    UserAttributes: [{ Name: "email", Value: email }],
  });
}

// ─────────────────────────────────────────────
// CONFIRM SIGN-UP — Cognito ConfirmSignUp
// Called from confirm.html with the code Cognito emailed after registration.
// ─────────────────────────────────────────────
async function confirmSignUp(email, code) {
  const cfg = _cfg();
  return _cognitoCall("ConfirmSignUp", {
    ClientId:         cfg.COGNITO_CLIENT_ID,
    Username:         email,
    ConfirmationCode: code,
  });
}

// ─────────────────────────────────────────────
// RESEND CONFIRMATION CODE
// ─────────────────────────────────────────────
async function resendConfirmationCode(email) {
  const cfg = _cfg();
  return _cognitoCall("ResendConfirmationCode", {
    ClientId: cfg.COGNITO_CLIENT_ID,
    Username: email,
  });
}

// ─────────────────────────────────────────────
// LOGIN — password → /send-otp Lambda → verify.html
// The Lambda validates credentials with Cognito server-side,
// then stores a 5-minute OTP in DynamoDB and emails it via SES.
// ─────────────────────────────────────────────
async function loginUser(email, password) {
  await _apiPost("send-otp", { email, password });
  // Store email so verify.html can include it in the /verify-otp call
  sessionStorage.setItem("otp_pending_email", email);
}

// ─────────────────────────────────────────────
// VERIFY OTP — /verify-otp Lambda
// On success, the Lambda returns {user_sub, email} which becomes the session.
// ─────────────────────────────────────────────
async function verifyOtpCode(otpCode) {
  const email = sessionStorage.getItem("otp_pending_email");
  if (!email) {
    return { valid: false, message: "Session expired. Please sign in again." };
  }

  try {
    const data = await _apiPost("verify-otp", { email, otp_code: otpCode });
    // Promote to full session
    sessionStorage.setItem("auth_user", JSON.stringify({
      user_sub: data.user_sub,
      email:    data.email,
      name:     data.email.split("@")[0],
    }));
    sessionStorage.removeItem("otp_pending_email");
    return { valid: true };
  } catch (err) {
    const msg = err.message || "Verification failed.";
    if (err.status === 401) {
      if (msg.includes("expired") || msg.includes("Session")) {
        sessionStorage.removeItem("otp_pending_email");
        return { valid: false, message: msg, expired: true };
      }
      return { valid: false, message: msg };
    }
    return { valid: false, message: "Something went wrong. Please try again." };
  }
}

// Legacy shim so existing verify.html `verifyOTP()` calls still work
function verifyOTP(_entered) {
  // This path is no longer used — verify.html now calls verifyOtpCode() directly.
  return { valid: false, message: "Please use the updated verify.html" };
}

// ─────────────────────────────────────────────
// FORGOT PASSWORD — two-step Cognito flow
// Step 1: forgotPassword(email)   → Cognito sends a code to the user
// Step 2: confirmForgotPassword(email, code, newPassword)
// ─────────────────────────────────────────────
async function forgotPassword(email) {
  const cfg = _cfg();
  return _cognitoCall("ForgotPassword", {
    ClientId: cfg.COGNITO_CLIENT_ID,
    Username: email,
  });
}

async function confirmForgotPassword(email, code, newPassword) {
  const cfg = _cfg();
  return _cognitoCall("ConfirmForgotPassword", {
    ClientId:         cfg.COGNITO_CLIENT_ID,
    Username:         email,
    ConfirmationCode: code,
    Password:         newPassword,
  });
}

// ─────────────────────────────────────────────
// SIGN OUT
// ─────────────────────────────────────────────
function signOut() {
  sessionStorage.removeItem("auth_user");
  sessionStorage.removeItem("otp_pending_email");
  window.location.href = "index.html";
}

// ─────────────────────────────────────────────
// SESSION HELPERS
// ─────────────────────────────────────────────
function getSessionUser() {
  const raw = sessionStorage.getItem("auth_user");
  return raw ? JSON.parse(raw) : null;
}

function requireAuth() {
  if (!getSessionUser()) window.location.href = "index.html";
}

// ─────────────────────────────────────────────
// PASSWORD VALIDATION (unchanged)
// ─────────────────────────────────────────────
const PWD_RULES = {
  length:    { test: v => v.length >= 8,           label: "8+ characters"     },
  uppercase: { test: v => /[A-Z]/.test(v),         label: "Uppercase letter"  },
  lowercase: { test: v => /[a-z]/.test(v),         label: "Lowercase letter"  },
  number:    { test: v => /[0-9]/.test(v),         label: "Number"            },
  special:   { test: v => /[^A-Za-z0-9]/.test(v), label: "Special character" },
};

function validatePassword(password) {
  const results = {};
  for (const [key, rule] of Object.entries(PWD_RULES)) {
    results[key] = rule.test(password);
  }
  return results;
}

function isPasswordValid(password) {
  return Object.values(validatePassword(password)).every(Boolean);
}

function updatePwdChecklist(password) {
  const results = validatePassword(password);
  for (const [key, passed] of Object.entries(results)) {
    const el = document.getElementById("rule-" + key);
    if (el) el.classList.toggle("pass", passed);
  }
}

// ─────────────────────────────────────────────
// FORM HELPERS (unchanged)
// ─────────────────────────────────────────────
function showError(inputEl, message) {
  inputEl.classList.add("error");
  const err = inputEl.parentElement.querySelector(".field-error");
  if (err) { err.textContent = message; err.classList.add("visible"); }
}

function clearError(inputEl) {
  inputEl.classList.remove("error");
  const err = inputEl.parentElement.querySelector(".field-error");
  if (err) err.classList.remove("visible");
}

function showAlert(id, message) {
  const el = document.getElementById(id);
  if (el) { el.textContent = message; el.classList.add("visible"); }
}

function hideAlert(id) {
  const el = document.getElementById(id);
  if (el) el.classList.remove("visible");
}

// ─────────────────────────────────────────────
// OTP INPUT AUTO-ADVANCE (verify.html) — unchanged
// ─────────────────────────────────────────────
function initOtpInputs() {
  const inputs = document.querySelectorAll(".otp-group input");
  inputs.forEach((input, i) => {
    input.addEventListener("input", e => {
      const val = e.target.value.replace(/\D/g, "").slice(-1);
      e.target.value = val;
      if (val && i < inputs.length - 1) inputs[i + 1].focus();
      checkOtpComplete(inputs);
    });
    input.addEventListener("keydown", e => {
      if (e.key === "Backspace" && !input.value && i > 0) inputs[i - 1].focus();
    });
    input.addEventListener("paste", e => {
      e.preventDefault();
      const pasted = e.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6);
      pasted.split("").forEach((ch, idx) => { if (inputs[idx]) inputs[idx].value = ch; });
      inputs[Math.min(pasted.length, inputs.length - 1)].focus();
      checkOtpComplete(inputs);
    });
  });
}

function getOtpValue() {
  return Array.from(document.querySelectorAll(".otp-group input")).map(i => i.value).join("");
}

function checkOtpComplete(inputs) {
  const complete = Array.from(inputs).every(i => i.value.length === 1);
  const btn = document.getElementById("verify-btn");
  if (btn) btn.disabled = !complete;
}

// ─────────────────────────────────────────────
// MAP COGNITO ERROR CODES TO USER MESSAGES
// ─────────────────────────────────────────────
function cognitoErrorMessage(err) {
  const code = err.code || "";
  if (code === "UsernameExistsException")     return "An account with this email already exists.";
  if (code === "InvalidPasswordException")    return "Password does not meet the requirements.";
  if (code === "InvalidParameterException")   return "Invalid email address.";
  if (code === "UserNotFoundException")       return "No account found with this email.";
  if (code === "NotAuthorizedException")      return "Incorrect email or password.";
  if (code === "UserNotConfirmedException")   return "Please verify your email first. Check your inbox.";
  if (code === "CodeMismatchException")       return "Incorrect verification code.";
  if (code === "ExpiredCodeException")        return "Verification code has expired. Please request a new one.";
  if (code === "LimitExceededException")      return "Too many attempts. Please try again later.";
  if (code === "TooManyRequestsException")    return "Too many requests. Please try again later.";
  if (code === "TooManyFailedAttemptsException") return "Too many failed attempts. Please try again later.";
  return err.message || "An unexpected error occurred. Please try again.";
}
